apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- serviceaccount.yaml
- certificate.yaml

images:
- name: testserver
  newName: rfinner/contour-authserver
  newTag: latest
